### ISSUE TITLE
Nested_top_taxa

### ISSUE THREAD

**Issue by weibokong27** [gmteunisse/fantaxtic#13]
Hi: 

Thank you for developing this excellent package! 

I want to map the Top 10 phyla, with 3 Order levels nested within each Phylum, but I am confused about the results. I don't see any Order shown in p__Firmicutes; however, taxonomy annotation results indicate that all p__Firmicutes are annotated to the Order level. 

`top_nested <- nested_top_taxa(ps,
                              top_tax_level = "Phylum",
                              nested_tax_level = "Order",
                              n_top_taxa = 9, 
                              n_nested_taxa = 3)

plot_nested_bar(ps_obj = top_nested$ps_obj,
                top_level = "Phylum",
                nested_level = "Order") + 
  facet_nested_wrap(~ SoilType + Deposition, scales = "free_x", nrow = 3)`

![联想截图_20230110122928](https://user-images.githubusercontent.com/56707103/211463206-b35b387d-bcde-4059-bfb0-44e93eaaeeaf.png)

I uploaded my data at the same time：

[ps.zip](https://github.com/gmteunisse/fantaxtic/files/10378931/ps.zip)

**Comment by gmteunisse** [comment]
Thanks for bringing this to my attention. I've replicated your problem. I'll try to implement a fix as soon as possible. My apologies for the inconvenience.

**Comment by gmteunisse** [comment]
I managed to trace down the error. Something went wrong in your `tax_table()`, and something went awry in the package (a 0/0 division resulted in NaNs). I've fixed the issue in the package in the latest commit, so make sure to reinstall the package. On your side, you need to make sure that your taxonomy table contains `NA` values in cells where no annotation is available, instead of  `'p_'`, `'o_'`, etc. You can do this by running the code chunk below:

```r
# Replace rank prefixes with an empty string
remove_rank_prefix <- function(str, unannotated_only=T){
  if(unannotated_only){
    pattern = "^[[:alpha:]]__$"
  } else {
    pattern = "^[[:alpha:]]__"
  }
  gsub(pattern, "", str)
}

# Remove the rank prefixes - NAs are required for tax glomming
tax_tab <- tax_table(ps) %>%
  as.data.frame() %>%
  mutate_all(remove_rank_prefix, unannotated_only=T) %>%
  mutate_all(~na_if(., '')) 
tax_table(ps) <- as.matrix(tax_tab)

```
