### ISSUE TITLE
Relative abundance option in get_top_taxa does not turn off

### ISSUE THREAD

**Issue by tiagobrc** [gmteunisse/Fantaxtic#2]
Hi,

Great package!!
I checked the code, and it seems to be related with the fantaxtic_barplot. It turns the table into relative abundance regardless of what the get_top_taxa does. Is it anything I can do? Did I do something wrong?

Thanks!

T

**Comment by gmteunisse** [comment]
Hi Tiago,

Thanks for using the package! I have been out of this field for a while, so excuse my late response.

Could you give me a bit more detail of what you are trying to achieve or what goes wrong, perhaps with some example code?

I'm also thinking that it might be my documentation that is not clear: `fantaxtic_barplot` was only intended to display relative abundances. I implemented it like this, because - in my experience - sequencing depth per sample can easily differ by a factor 10, making the results after plotting very hard to interpret. Would you be helped if you could plot the raw counts?

**Comment by tiagobrc** [comment]
Hi Thanks for helping!
Thanks for implementing this package, it is easier to plot relative abundances than phyloseq itself.

in get_top_taxa, we have the option: relative  = TRUE.
I thought would be possible to turn this off by using relative  = FALSE.

But it does not happen. It seems that fantaxtic plot always converts it to relative regardless of relative  = TRUE/FALSE.


Thanks!!

**Comment by gmteunisse** [comment]
Hi Tiago,

The relative = TRUE option in `get_top_taxa` only help with the selection
of your top taxa, but is not transferred through to the `fantaxtic_bar
function`. There are (at least) two ways of defining the "most abundant
taxa", namely the raw number of reads per taxon, or the relative number of
reads per taxon, which I think is more useful. If you take the raw number
of reads, the "most abundant taxa" get heavily influenced by samples with
more reads, leading to skewed results.

I could add a similar variable to `fantaxtic_bar`, but I think the results
will become hard to interpret due to large intersample reads variation. Let
me know what you think.

**Comment by tiagobrc** [comment]
Thanks for the clarification.
after your explanation, I think it is not necessary to plot the raw data indeed.

Thanks!!
