### ISSUE TITLE
How to install fantaxtic package?

### ISSUE THREAD

**Issue by Pratiksha202311** [gmteunisse/fantaxtic#24]
Hello,
I am trying to install the package from both devtools and remotes however I end up all the time with these errors. 

if(!"devtools" %in% installed.packages()){ +  install.packages("devtools") + } 
> devtools::install_github("gmteunisse/fantaxtic") 
Downloading GitHub repo gmteunisse/fantaxtic@HEAD Error in utils::download.file(url, path, method = method, quiet = quiet,  :    cannot open URL 'https://api.github.com/repos/gmteunisse/fantaxtic/tarball/HEAD' 
> devtools::install_github("gmteunisse/ggnested")
 Downloading GitHub repo gmteunisse/ggnested@HEAD Error in utils::download.file(url, path, method = method, quiet = quiet,  :    cannot open URL 'https://api.github.com/repos/gmteunisse/ggnested/tarball/HEAD'
--

> if (!require("remotes")) { +  install.packages("remotes") + } 
> remotes::install_github("gmteunisse/fantaxtic") 
Downloading GitHub repo gmteunisse/fantaxtic@HEAD Error in utils::download.file(url, path, method = method, quiet = quiet,  :    cannot open URL 'https://api.github.com/repos/gmteunisse/fantaxtic/tarball/HEAD' 
> require("fantaxtic") 
Loading required package: fantaxtic Warning message: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :   there is no package called ‘fantaxtic’
--
 
 It would be a great help if you could guide me for finding problem and tentative solution for it! |

**Comment by gmteunisse** [comment]
I couldn't reproduce your error on my machines. It could be that you're behind a firewall, or that something in your system's configuration is preventing you from downloading the package. I'm sorry I can't help you with your issue. I hope that a bit of googling of the error can help you resolve it! See below for a few suggestions.

* In [the issue here](https://github.com/r-lib/remotes/issues/130) it is suggsted to set `method="libcurl"` using the `remotes` package. 
* In [this StackOverflow post](https://stackoverflow.com/questions/53845962/having-trouble-getting-devtoolsinstall-github-to-work-in-r-on-win-7-64bit-ma) it is suggested to run `options(download.file.method = "wininet")`
