### ISSUE TITLE
n_taxa = is not working for me

### ISSUE THREAD

**Issue by momodiame21** [gmteunisse/fantaxtic#31]
The n_taxa option does not work for me. Please see below. Also the tax_level = "" option doesnt work. It brings this error 
unused arguments (n_taxa = 10, tax_level = "Species")
> top_asv <- top_taxa(GlobalPatterns, n_taxa = 10) 
Error in top_taxa(GlobalPatterns, n_taxa = 10) :    unused argument (n_taxa = 10) 
> top_asv <- top_taxa(GlobalPatterns) 
>

**Comment by gmteunisse** [comment]
Hello, can you please provide your session info? I think you are using microbiome::top_taxa rather than fantaxtic::top_taxa.

PS I answered your other issue, but never heard back from you. By the sound of it, your other issue has been resolved - please let me know if the provided solution resolved your issue, and if so, close the issue.
________________________________
From: momodiame21 ***@***.***>
Sent: Tuesday, April 30, 2024 11:05:03 AM
To: gmteunisse/fantaxtic ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [gmteunisse/fantaxtic] n_taxa = is not working for me (Issue #31)


The n_taxa option does not work for me. Please see below. Also the tax_level = "" option doesnt work. It brings this error
unused arguments (n_taxa = 10, tax_level = "Species")

top_asv <- top_taxa(GlobalPatterns, n_taxa = 10)
Error in top_taxa(GlobalPatterns, n_taxa = 10) : unused argument (n_taxa = 10)
top_asv <- top_taxa(GlobalPatterns)

**Comment by momodiame21** [comment]
Thanks. I unloaded microbiome and the top_taxa is now working for fantaxtic.
